### ISSUE TITLE
Version 0.2.0 doesn't compile, missing sys.rs?

### ISSUE THREAD

**Issue by davidko** [lfairy/rust-errno#10]
Commit 45c353dbe069952e6a8679b4d498ab0ff3032eea introduces a line in lib.rs:9 "mod sys;", but there is no sys.rs or sys/mod.rs committed. Is this a missing file?

Related: When I try to compile errno 0.2.0, I get:

/home/dko/.cargo/registry/src/github.com-1ecc6299db9ec823/errno-0.2.0/src/lib.rs:9:5: 9:8 error: file not found for module `sys`
/home/dko/.cargo/registry/src/github.com-1ecc6299db9ec823/errno-0.2.0/src/lib.rs:9 mod sys;
                                                                                       ^~~
/home/dko/.cargo/registry/src/github.com-1ecc6299db9ec823/errno-0.2.0/src/lib.rs:9:5: 9:8 help: name the file either sys.rs or sys/mod.rs inside the directory "/home/dko/.cargo/registry/src/github.com-1ecc6299db9ec823/errno-0.2.0/src"
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
error: Could not compile `errno`.

To learn more, run the command again with --verbose.

**Comment by lfairy** [comment]
There is no `sys.rs`, because the code uses the [`#[cfg_attr]`](https://doc.rust-lang.org/book/conditional-compilation.html#cfg_attr) attribute to select either `unix.rs` or `windows.rs` depending on the platform.

Can you give me more info about your platform, rustc version, etc.? I haven't been able to reproduce that error, whether on my machine or on CI.

**Comment by davidko** [comment]
Ah hah, interesting.

Looks like I'm using rustc 1.10.0 (cfcb716cf 2016-07-03) . I'm using Ubuntu
16.04, 64-bit. Perhaps my rustc is too old? Looks like 1.13.0 is the latest
one. I'll try that out...

**Comment by lfairy** [comment]
Aha! It's probably rust-lang/rust#25544, which was fixed after 1.10 was released. If the issue is what I think it is, then upgrading should fix the problem.

**Comment by lfairy** [comment]
I did some testing. Rust 1.12 accepts the code without error, but Rust 1.11 fails with the error you describe.

I'll refactor the code so that it works on both.

**Comment by lfairy** [comment]
Released as [0.2.1](https://crates.io/crates/errno/0.2.1). Thanks for reporting!

**Comment by davidko** [comment]
Thank you for your help! :)

- David
