### ISSUE TITLE
impl Into for Error?

### ISSUE THREAD

**Issue by dodomorandi** [lfairy/rust-errno#12]
If you want to wrap a `libc` error using `io::Error::from_raw_os_error`, a raw `i32` is needed. However, it is not possible to use `errno::errno` to do so, just because it cannot be converted. Even if I am against implicit conversions, in this case it could be useful to have some sort of explicit conversion, `impl`ementing `AsRef` or, probably better, `Into` for `Error`.

**Comment by lfairy** [comment]
`AsRef` won't work because of lifetimes, but I think `Into` is a good idea. I would accept a PR for the latter.

**Comment by dodomorandi** [comment]
I completely agree. `AsRef` would be really bad for this case. I will probably send you a PR tomorrow. Thanks!

**Comment by lfairy** [comment]
Implemented in #13
