### ISSUE TITLE
Port library to winapi 0.3

### ISSUE THREAD

**Issue by lfairy** [lfairy/rust-errno#14]
`errno` uses `winapi` 0.2 right now. We need to update it to use `winapi` 0.3 instead.

We will need to remove the `kernel32-sys` dependency, and add appropriate feature flags to the `winapi` dependency. See the [winapi FAQ](https://github.com/retep998/winapi-rs/blob/0.3/README.md#frequently-asked-questions) for advice on how to do this.

Whoever takes on this task should also have a Windows environment to test with.

**Comment by ErichDonGubler** [comment]
More than happy to take this on -- I've been doing a fair amount of tinkering with `winapi` as of late. :)
