### ISSUE TITLE
FormatMessageW may get you non-error description.

### ISSUE THREAD

**Issue by DoumanAsh** [lfairy/rust-errno#2]
FormatMessageW can return some shit in case of non-error code.
You can distinguish it by checking last two symbols(i.e Windows new line)

If there is no new line on the end, then this is, most possibly, is not error.
It is not error case of course :)

JFYI

**Comment by lfairy** [comment]
Thanks for the info. I'm going to close this issue because I think the current behavior is okay. Feel free to reopen if you disagree.

**Comment by DoumanAsh** [comment]
It is really up to you... Generally it is system responsibility to use right errors so i don't think it is critical or anything.

Btw,
https://github.com/lfairy/rust-errno/blob/master/src/windows.rs#L51-L52

I don't really understand why you need to truncate if you can just write ```msg.trim_right()```?
