### ISSUE TITLE
Implement Deref for Errno type

### ISSUE THREAD

**Issue by jeandudey** [lfairy/rust-errno#8]
Implement `Deref` and possibly `DerefMut` for `Errno` type so instead of doing this:
```rust
let e = errno();
println!("{}", e.0);
```
We do this:
```rust
let e = errno();
println!("{}", e);
```

**Comment by lfairy** [comment]
Thanks for reporting.

The Errno type has its own Display instance already, so adding a Deref instance wouldn't help with that. Also, Errno is not a smart pointer or collection and so a Deref impl would be surprising.

Unless there are other reasons to add such an impl, I'm going to close this issue.
