### ISSUE TITLE
Show message on Debug.

### ISSUE THREAD

**Issue by kevincox** [lfairy/rust-errno#9]
The Debug format is for the developer and supposed to be descriptive. Currently it just shows the errno number for which there is no very easy way to map to a value. The Debug should show the message as well as the number so that issues are easy to debug.

This is especially important because `unwrap` uses debug to format the error value which is a very common case for errno.

**Comment by lfairy** [comment]
Good point! I've implemented this in 2d1c0252b5c83129c8dc3c4b22c6ba6fc7b14d97.

What do you think about this approach?

**Comment by kevincox** [comment]
That looks good to me :) Thanks.

**Comment by lfairy** [comment]
Published as [0.2.0](https://crates.io/crates/errno/0.2.0).

**Comment by kevincox** [comment]
\o/ I just updated and have already been glad to see the message.
